title: ðŸ  è¨˜å¸³
email: ray120424@gmail.com
description: >-
  è¨˜å¸³ç³»çµ±
baseurl: "/accounting"
url: ""
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - expense.md
  - budget.md
  - setting.md